### ISSUE TITLE
JFT Reading discrepancy on Dec 21.

### ISSUE THREAD

**Issue by devyces** [bmlt-enabled/fetch-jft#31]
Reading content from published paper book and JFT email list are different from content served from fetch-jft.

![image](https://github.com/user-attachments/assets/e77fe944-b75b-4dc1-b000-6f719b05e180)
![image](https://github.com/user-attachments/assets/ee595d24-2a80-41a4-be73-b00192a771f6)

**Comment by tempsaint** [comment]
The issue is with what NAWS is feeding. I'm not sure where New Zealand list get their source from but this is the NAWS website and the email they send out... 

<img width="1077" alt="image" src="https://github.com/user-attachments/assets/4422200d-87fe-46c9-92da-e8ee17ea0acd" />

<img width="1216" alt="image" src="https://github.com/user-attachments/assets/81ff5423-84d7-4209-b75d-f270b9e404a7" />

**Comment by devyces** [comment]
Will relay this to the person who reported it and they can follow up if desired.
Thanks for your service!!

**Comment by pjaudiomv** [comment]
Yes this is not an issue with plugin as we pull data directly from naws, id reach out to their web team
